### ISSUE TITLE
Error UTF-8 when install de plugin

### ISSUE THREAD

**Issue by LMachucaORT** [Panopto/Panopto-Button-for-Atto#23]
Hello, after the installation the plugin moodle say me:
 "!! Unicode!! [System] must be installed/activated - You need to store all your data in Unicode (UTF-8) format. The new installations were run on databases whose set of default non-Unicode characters. If you are doing a upgrade, you should go through the UTF-8 migration process (see about it on the Administration page)."
We can't update the database because some tables give an error with this encoding, you could tell us which tables this particular plugin affects, so that we can install with this modification
![Screenshot from 2022-05-11 04](https://user-images.githubusercontent.com/98826878/167911081-14197bc3-eba4-41a7-9b22-47cc3cfa59bd.png)
.

**Comment by jmalmsten-panopto** [comment]
Hi,

This plug-in actually has no control over any tables in the Moodle DB, it uses the DB global to get values from a table created by the Panopto Block plug-in. The only table this plug-in references is 'block_panopto_foldermap' but I doubt that is your issue.

I think this is an issue with how the database on this Moodle installation was set up, based off some quick web searching it looks like this is an issue common when using tools like Fantastico to create your Moodle environment. It also looks like this could be an issue when migrating to PHP 8, below is a link to a thread and the solutions those users found for their issue. 

- https://moodle.org/mod/forum/discuss.php?d=434100#p1761944
- https://tracker.moodle.org/browse/MDL-74616


I would suggest making sure all of your Moodle tables are using UTF8 so prevent seeing this issue in the future. Below are some more links on similar issues I found that may be helpful. Note: Some of these links are very old and might not be applicable to your issue, see the warning on the UTF-8_migration link below for an example.

- https://docs.moodle.org/dev/UTF-8_migration
- https://moodle.org/mod/forum/discuss.php?d=77219


I do not think this issue is related to the plug-in so I will be closing this issue at this time. 

Thank you,
Joe Malmsten
